server:
  port: 8082
spring:
  webflux:
    session:
      timeout: 30m
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/reactive_security
    username: user
    password: user
  rabbitmq:
    host: localhost
    port: 5673
    username: user
    password: user

exchange:
  lecture: x.lecture
queues:
  lecture: q.lecture
routing_key:
  lecture: lecture
timezone:
  zone: America/Bogota
jwt:
  secret: 5846N5QiFhER0b8mGvffheyPoueFjPtRKDZNDDHShSegBIetprU6kkjhg
  expiration: 30

cors:
  domain: http://192.168.100.153:4200
  allowed-origins:
    - "*"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed-headers:
    - authorization
    - content-type
    - origin
  allowed-credentials: false
logging:
  level:
    org:
      springframework:
        amqp: ERROR